/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package purchasemgmtsys;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Properties;
import java.sql.*;
import javax.swing.*;
import java.awt.*; 
import java.awt.event.*;
import javax.swing.table.*;

/**
 *
 * @author kshitij
 */
public class Vendors extends javax.swing.JFrame {
    String vendor_id;

    /**
     * Creates new form Vendors
     */
    public Vendors() {
       vendor_id=JOptionPane.showInputDialog("Enter vendor id");
       initComponents();
       this.setLocationRelativeTo(null);
       
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txt1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        txt2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        txt3 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Vendor name");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Contact");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Location");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Show all Vendors");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Vendor_name", "Location", "Contact_number", "Vendor_id"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Vendor Details");

        jButton5.setText("HOME");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "First_Name", "Last_Name", "Emp_Id", "adress", "Mobile"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel2.setText("Employee Details for given Vendor ID");

        jButton6.setText("Get Employee Details");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                    .addComponent(txt2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(176, 176, 176)
                                .addComponent(jButton5))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(437, 437, 437)
                        .addComponent(jButton6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2)
                                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton3)
                                    .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Connection conn1;
conn1 = null;
try {
            // connect way #1
            String url1 = "jdbc:mysql://localhost:3306/project";
            String user = "root";
            String password = "";
            conn1 = DriverManager.getConnection(url1, user, password);
            
        } catch (SQLException ex) {
            
        }
System.out.println("Connection Successfuly Estabilished");
try{
            if (conn1 != null) {
                //System.out.println("Connected to the database test1");
                String sql ="SELECT * FROM Vendors where vendor_id=\"" + vendor_id + "\"" + ";";
                Statement statement = conn1.createStatement();
                ResultSet result = statement.executeQuery(sql);
                while (result.next())
                {
                    String vendor_name = result.getString("vendor_name");
                    txt1.setText(vendor_name);
                }
                }
}
catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, "A connection could not be made with the Database. \nPlease check your connectivity or contact the system administrator.");
            //System.out.println("An error occurred. Maybe user/password is invalid");
            ex.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
Connection conn1;
conn1 = null;
try {
            // connect way #1
            String url1 = "jdbc:mysql://localhost:3306/project";
            String user = "root";
            String password = "";
            conn1 = DriverManager.getConnection(url1, user, password);
            
        } catch (SQLException ex) {
            
        }
System.out.println("Connection Successfuly Estabilished");
try{
            if (conn1 != null) {
                //System.out.println("Connected to the database test1");
                String sql = "SELECT * FROM Vendors ;";
                Statement statement = conn1.createStatement();
                ResultSet result = statement.executeQuery(sql);
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);
                while (result.next())
                {
                    String vendor_name = result.getString("vendor_name");
                    String location= result.getString("location");
                    String Contact_number= result.getString("Contact_number");
                    String ven_id= result.getString("Vendor_id");
                    jTable1.setVisible(true);
                    
                    model.addRow(new Object[]{vendor_name,location,Contact_number,ven_id});
                }
                }
}
catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, "A connection could not be made with the Database. \nPlease check your connectivity or contact the system administrator.");
            //System.out.println("An error occurred. Maybe user/password is invalid");
            ex.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Connection conn1;
conn1 = null;
try {
            // connect way #1
            String url1 = "jdbc:mysql://localhost:3306/project";
            String user = "root";
            String password = "";
            conn1 = DriverManager.getConnection(url1, user, password);
            
        } catch (SQLException ex) {
            
        }
System.out.println("Connection Successfuly Estabilished");
try{
            if (conn1 != null) {
                //System.out.println("Connected to the database test1");
                String sql ="SELECT * FROM Vendors where vendor_id=\"" + vendor_id + "\"" + ";";
                Statement statement = conn1.createStatement();
                ResultSet result = statement.executeQuery(sql);
                while (result.next())
                {
                    String contact = result.getString("contact_number");
                    txt2.setText(contact);
                }
                }
}
catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, "A connection could not be made with the Database. \nPlease check your connectivity or contact the system administrator.");
            //System.out.println("An error occurred. Maybe user/password is invalid");
            ex.printStackTrace();
        }        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
Connection conn1;
conn1 = null;
try {
            // connect way #1
            String url1 = "jdbc:mysql://localhost:3306/project";
            String user = "root";
            String password = "";
            conn1 = DriverManager.getConnection(url1, user, password);
            
        } catch (SQLException ex) {
            
        }
System.out.println("Connection Successfuly Estabilished");
try{
            if (conn1 != null) {
                //System.out.println("Connected to the database test1");
                String sql ="SELECT * FROM Vendors where vendor_id=\"" + vendor_id + "\"" + ";";
                Statement statement = conn1.createStatement();
                ResultSet result = statement.executeQuery(sql);
                while (result.next())
                {
                    String location = result.getString("location");
                    txt3.setText(location);
                }
                }
}
catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, "A connection could not be made with the Database. \nPlease check your connectivity or contact the system administrator.");
            //System.out.println("An error occurred. Maybe user/password is invalid");
            ex.printStackTrace();
        }        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
this.setVisible(false);
        new NewJFrame1().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
Connection conn1;
conn1 = null;
try {
            // connect way #1
            String url1 = "jdbc:mysql://localhost:3306/project";
            String user = "root";
            String password = "";
            conn1 = DriverManager.getConnection(url1, user, password);
            
        } catch (SQLException ex) {
            
        }
System.out.println("Connection Successfuly Estabilished");
try{
            if (conn1 != null) {
                //System.out.println("Connected to the database test1");
                String sql = "SELECT * FROM Employee where vendor_id ="+vendor_id+";";
                Statement statement = conn1.createStatement();
                ResultSet result = statement.executeQuery(sql);
                DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
                model.setRowCount(0);
                while (result.next())
                {
                    String first_name = result.getString("first_name");
                    String last_name= result.getString("last_name");
                    String emp_id= result.getString("emp_id");
                    String address= result.getString("address");
                    String mobile= result.getString("mobile_number");
                    jTable1.setVisible(true);
                    
                    model.addRow(new Object[]{first_name,last_name,emp_id,address,mobile});
                }
                }
}
catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, "A connection could not be made with the Database. \nPlease check your connectivity or contact the system administrator.");
            //System.out.println("An error occurred. Maybe user/password is invalid");
            ex.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vendors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vendors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vendors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vendors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vendors().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    // End of variables declaration//GEN-END:variables
}
